[fix] add code to eval API_LIBRARY from ENV_DIR (positiona param $3) in bin/compile

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -4,6 +4,6 @@ BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
 
-ls -la "$ENV_DIR"
+[ ! -f "$ENV_DIR/API_LIBRARY" ] && echo "\$API_LIBRARY config not found" && exit 1
 
-echo "lib2app compatible project …"
+echo "lib2app project"
